name: ktlint

on:
  pull_request:
    branches: [ main ]

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "format with ktlint"
        uses: "vroy/gha-kotlin-linter@v1"

      - name: "git add & git commit"
        if: failure()
        run: |
          git config --global user.name 'ktlint'
          git add --all
          git commit -m 'code automatically formatted with ktlint'