name: CI-format-with-ktlint

on:
  pull_request:
    branches: [ main ]

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: "format with ktlint"
        run: "mvn com.github.gantsign.maven:ktlint-maven-plugin:format"

      - name: "commit changes"
        run: |
          git config --global user.name 'BRGL'
          git add --all
          git status
          git commit -m "code automatically formatted with ktlint"
          git status
