name: ktlint

on:
  pull_request:
    branches: [ main ]

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: "check format with ktlint"
        run: "mvn com.github.gantsign.maven:ktlint-maven-plugin:check"

      - name: "format with ktlint"
        if: failure()
        run: "mvn com.github.gantsign.maven:ktlint-maven-plugin:format"

      - name: "commit changes"
        if: failure()
        run: |
          git config --global user.name 'ktlint'
          git add --all
          git commit -m "code automatically formatted with ktlint"
          git push
